[build]
  publish = "public"
  functions = "functions"
  command = "npm run build"

[dev]
  port = 8888
  targetPort = 1313
  framework = "#custom"
  functions = "src/functions"
  command = "hugo server --bind 0.0.0.0 --baseURL http://localhost:1313"

[[plugins]]
  package = "netlify-plugin-threadtalkjs"

[[redirects]]
  from = "https://threadtalkjs.netlify.app/*"
  to = "https://www.threadtalkjs.ml/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404/"
  status = 404
  
  [[headers]]
  for = "/404/*"
  [headers.values]
    custom = "foo"
